layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  codingames: Mglt-b
  # dribbble: your_username
  # facebook: your_username
  hackerrank: bastien_miglior1
  # instagram: your_username
  # keybase: your_username
  linkedin: bastien-miglior1
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/community/logos/python-logo-only.png

  - name: Kivy Framework
    web_url: https://kivy.org/
    image_url: https://raw.githubusercontent.com/kivy/kivy/master/kivy/data/logo/kivy-icon-256.png

  - name: Microsoft Visual Basic
    web_url: https://learn.microsoft.com/fr-fr/dotnet/visual-basic/
    image_url: https://raw.githubusercontent.com/github/explore/71e4a0fc524fd1d7a0d9a940aa6b91f31458a87b/topics/vba/vba.png
